export const ROUTE_URL = {
  HOME: "",
  DASHBOARD: "/",
  DASHBOARD_CONSUMER: "/dashboard",
  LOGIN: "/login",
  REGISTER: "/register",
  FORGET_PASSWORD: "/forget-password",
  UNDEFINED: "*",
  ABOUT: "/about",
  NOT_ALLOWED: "/not-allowed",
  ADMIN: {
    BASE: "/admin",
    TENANT: {
      BASE: "/tenant",
      LIST: "",
      DETAIL: ":id",
      EDIT: "edit/:id",
      ADD: "add/:id",
    },
    ROLE: {
      BASE: "/role",
      LIST: "",
      DETAIL: ":id",
      EDIT: "edit/:id",
      ADD: "add",
    },
    USER: {
      BASE: "/user",
      LIST: "",
      DETAIL: ":id",
      EDIT: "edit/:id",
      ADD: "add",
      PERMISSIONS: "permissions/:id",
    },
    STATUS: {
      BASE: "/user",
      LIST: "",
      DETAIL: ":id",
      EDIT: "edit/:id",
      ADD: "add",
      PERMISSIONS: "permissions/:id",
    },
  },
  MASTERS: {
    BASE: "/master",
    BRAND: {
      BASE: "/brand",
      LIST: "",
      EDIT: "edit/:id",
      ADD: "add",
    },
  },
  STATUS: {
    LIST: "/status",
    DETAIL: ":id",
    EDIT: "/status/:id",
    ADD: "/status/add",
    PERMISSIONS: "permissions/:id",
  },
  CONTAINER: {
    LIST: "/container",
    DETAIL: ":id",
    EDIT: "/container/:id",
    ADD: "/container/add",
    PERMISSIONS: "permissions/:id",
  },
  ROLE: {
    LIST: "/role",
    DETAIL: ":id",
    EDIT: "/role/:id",
    ADD: "/role/add",
    PERMISSIONS: "permissions/:id",
  },
  USER: {
    LIST: "/user",
    DETAIL: ":id",
    EDIT: "/user/:id",
    ADD: "/user/add",
    PERMISSIONS: "permissions/:id",
  },
  ASSIGNCONTAINER: {
    LIST: "/assign-container",
    DETAIL: "/assign-container/:id",
    EDIT: "/assign-container/:id",
    ADD: "/assign-container/add",
    PERMISSIONS: "permissions/:id",
  },
  DISPATCHCONTAINER: {
    LIST: "/dispatch-container",
    DETAIL: "/assign-container/:id",
    EDIT: "/assign-container/edit/:id",
    ADD: "/assign-container/add",
    PERMISSIONS: "permissions/:id",
  },
  ASSIGNTOVENDOR: {
    LIST: "/assign-to-vendor",
    DETAIL: "/assign-to-vendor/:id",
    EDIT: "/assign-to-vendor/edit/:id",
    ADD: "/assign-to-vendor/add",
    PERMISSIONS: "permissions/:id",
  },
  ASSIGNTOCUSTOMER: {
    LIST: "/assign-to-customer",
    DETAIL: "/assign-to-customer/:id",
    EDIT: "/assign-to-customer/edit/:id",
    ADD: "/assign-to-customer/add",
    PERMISSIONS: "permissions/:id",
  },
  ASSIGNTOADMIN: {
    LIST: "/assign-to-admin",
    DETAIL: "/assign-to-admin/:id",
    EDIT: "/assign-to-admin/edit/:id",
    ADD: "/assign-to-admin/add",
    PERMISSIONS: "permissions/:id",
  },
  TRANSACTION: {
    LIST: "/view-transaction",
    DETAIL: "/view-transaction/:id",
    EDIT: "/view-transaction/edit/:id",
    ADD: "/view-transaction/add",
    PERMISSIONS: "permissions/:id",
  },
  TRANSACTION_MASTER: {
    LIST: "/transaction",
    // DETAIL: "/transaction/:id",
    EDIT: "/transaction/:id",
    ADD: "/transaction/add",
    PERMISSIONS: "permissions/:id",
  },
  TRACK_FLOW_STATUS: {
    LIST: "/track-flow-status",
    DETAIL: "/transaction/:id",
    EDIT: "/transaction/edit/:id",
    ADD: "/transaction/add",
    PERMISSIONS: "permissions/:id",
  },
  USER_STOCK_MANAGEMENT: {
    LIST: "/user-stock-management",
    DETAIL: "/transaction/:id",
    EDIT: "/transaction/edit/:id",
    ADD: "/transaction/add",
    PERMISSIONS: "permissions/:id",
  },
  CONTAINERMOVEMENT: {
    LIST: "/container-movement",
    DETAIL: "/container-movement/:id",
    EDIT: "/container-movement/edit/:id",
    ADD: "/container-movement/add",
    PERMISSIONS: "permissions/:id",
  },
  STOCKCONTAINER: {
    LIST: "/stock-container",
    DETAIL: "/stock-container/:id",
    EDIT: "/stock-container/edit/:id",
    ADD: "/stock-container/add",
    PERMISSIONS: "permissions/:id",
  },
  CONSUMERALLOTMENT: {
    LIST: "/consumer-allotment",
    DETAIL: "/consumer-allotment/:id",
    EDIT: "/consumer-allotment/edit/:id",
    ADD: "/consumer-allotment/add",
    PERMISSIONS: "permissions/:id",
  },
  VENDORALLOTMENT: {
    LIST: "/vendor-allotment",
    DETAIL: "/vendor-allotment/:id",
    EDIT: "/vendor-allotment/edit/:id",
    ADD: "/vendor-allotment/add",
    PERMISSIONS: "permissions/:id",
  },
  CUSTOMERALLOTMENT: {
    LIST: "/customer-allotment",
    DETAIL: "/customer-allotment/:id",
    EDIT: "/customer-allotment/edit/:id",
    ADD: "/customer-allotment/add",
    PERMISSIONS: "permissions/:id",
  },
  RECEIVEASSIGNCONTAINER: {
    LIST: "/receive-assign-container",
  
  },
};
